/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teampro;

/**
 *
 * @author Network lab
 */
public class three extends javax.swing.JFrame {

    /**
     * Creates new form three
     */
    public three() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSCalendar1 = new rojeru_san.componentes.RSCalendar();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDestination = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonEconomy1 = new javax.swing.JRadioButton();
        jRadioButtonFirstClass1 = new javax.swing.JRadioButton();
        jTextFieldPassenger1 = new javax.swing.JTextField();
        jComboBoxTime = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        submit = new rojeru_san.complementos.RSButtonHover();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonSingle1 = new javax.swing.JRadioButton();
        jRadioButtonReturn1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(225, 116, 93));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("Destinantion ");

        jComboBoxDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Destination ", "Hyderabad", "New Delhi", "Pune", "Vizag", "Banglore", "Gujrath" }));
        jComboBoxDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDestinationActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("Date of Journey");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Departure");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("No. of Passengers ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("Class");

        jRadioButtonEconomy1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jRadioButtonEconomy1.setText("Economy");
        jRadioButtonEconomy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEconomy1ActionPerformed(evt);
            }
        });

        jRadioButtonFirstClass1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jRadioButtonFirstClass1.setText("First Class");
        jRadioButtonFirstClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFirstClass1ActionPerformed(evt);
            }
        });

        jComboBoxTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Time", "11:30", "12:30", "1:30", "2:30" }));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("Ticket Type ");

        jRadioButtonSingle1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jRadioButtonSingle1.setText("Single");
        jRadioButtonSingle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSingle1ActionPerformed(evt);
            }
        });

        jRadioButtonReturn1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jRadioButtonReturn1.setText("Return");
        jRadioButtonReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReturn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPassenger1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonFirstClass1)
                                            .addComponent(jRadioButtonSingle1))
                                        .addGap(189, 189, 189)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonReturn1)
                                            .addComponent(jRadioButtonEconomy1))))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxDestination, 0, 480, Short.MAX_VALUE)
                                .addComponent(jComboBoxTime, 0, 480, Short.MAX_VALUE)
                                .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButtonEconomy1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioButtonFirstClass1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonReturn1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonSingle1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPassenger1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxDestination, jComboBoxTime, jDateChooser, jRadioButtonEconomy1, jRadioButtonFirstClass1, jTextFieldPassenger1});

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("BUS TICKET INFO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDestinationActionPerformed

    private void jRadioButtonEconomy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEconomy1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonEconomy1.isSelected()){
            jRadioButtonFirstClass1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEconomy1ActionPerformed

    private void jRadioButtonFirstClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFirstClass1ActionPerformed
        // TODO add your handling code here
        if(jRadioButtonFirstClass1.isSelected()){
            jRadioButtonEconomy1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFirstClass1ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void jRadioButtonSingle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSingle1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonSingle1.isSelected()){
            jRadioButtonReturn1.setSelected(false);}
    }//GEN-LAST:event_jRadioButtonSingle1ActionPerformed

    private void jRadioButtonReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReturn1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonReturn1.isSelected()){
            jRadioButtonSingle1.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonReturn1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        five x=new five();
        
        int fare=200;
        int Tax = 15;
        int miles = 0;
        int Tfare =0;
        int Dtax=0;
        int SubTotal = 0;
      
       if(jComboBoxDestination.getSelectedItem().equals("Pune") && jRadioButtonFirstClass1.isSelected()&& 
               jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
    
        int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Pune");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
           miles = 6;
           Tfare= (miles*fare)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
         
       }
        else if(jComboBoxDestination.getSelectedItem().equals("Pune") && jRadioButtonEconomy1.isSelected()&& 
                jRadioButtonSingle1.isSelected() && (!(jTextFieldPassenger1.getText()== null) )){
          int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Pune");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
      
           miles = 6;
           Tfare= miles*fare;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
          if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
        else if(jComboBoxDestination.getSelectedItem().equals("Pune") && jRadioButtonFirstClass1.isSelected()&& 
               jRadioButtonReturn1.isSelected() && (!(jTextFieldPassenger1.getText()== null)) ){
           int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Pune");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
          miles = 6;
           Tfare= (miles*fare*2)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
          if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
        else if(jComboBoxDestination.getSelectedItem().equals("Pune") && jRadioButtonEconomy1.isSelected()&& 
                jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
          int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Pune");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
           miles = 6;
           Tfare= miles*fare*2;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else if(jComboBoxTime.getSelectedItem().equals("Select Time")){
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Gujrath")&& jRadioButtonEconomy1.isSelected()&& 
               jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
     int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
      five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Gujrath");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("One Way");       
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
              miles = 4;
           Tfare= miles*fare;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Gujrath") && jRadioButtonFirstClass1.isSelected() && 
               jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
           int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Gujrath");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
                  miles = 4;
           Tfare= (miles*fare)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
          if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else{
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Gujrath")&& jRadioButtonEconomy1.isSelected()&& 
               jRadioButtonReturn1.isSelected() && (!(jTextFieldPassenger1.getText()== null) )){
      int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Gujrath");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("Binalabagan");
       
       miles = 4;
           Tfare= miles*fare*2;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
           if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Gujrath") && jRadioButtonFirstClass1.isSelected() && 
               jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
       int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Gujrath");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("Round Trip");
      five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
      
           miles = 4;
           Tfare= (miles*fare*2)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
          if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Vizag") && jRadioButtonEconomy1.isSelected() 
               && jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
       int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Vizag");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
       miles = 5;
           Tfare= miles*fare*2;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
          if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
           else if(jComboBoxDestination.getSelectedItem().equals("Vizag") && jRadioButtonFirstClass1.isSelected()
                   && jRadioButtonReturn1.isSelected() && (!(jTextFieldPassenger1.getText()== null) )){
          int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Vizag");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("Round Trip");
      five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
           miles = 5;
           Tfare= (miles*fare*2)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
       if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Vizag") && jRadioButtonEconomy1.isSelected()
               && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
       int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Vizag");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
      
       miles = 5;
           Tfare= miles*fare;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
   if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
           else if(jComboBoxDestination.getSelectedItem().equals("Vizag") && jRadioButtonFirstClass1.isSelected()
                   && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
      int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Vizag");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
      
           miles = 5;
           Tfare= (miles*fare)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Banglore")&& jRadioButtonEconomy1.isSelected()
               && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
       int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
   
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Banglore");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
       miles = 7;
           Tfare= miles*fare;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
          else if(jComboBoxDestination.getSelectedItem().equals("Banglore") && jRadioButtonFirstClass1.isSelected()
                  && jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
         int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Banglore");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
           miles = 7;
           Tfare= (miles*fare*2)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*(Pass);
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
        if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
          else if(jComboBoxDestination.getSelectedItem().equals("Banglore")&& jRadioButtonEconomy1.isSelected()
               && jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
       int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Banglore");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
       miles = 7;
           Tfare= miles*fare*2;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
          else if(jComboBoxDestination.getSelectedItem().equals("Banglore") && jRadioButtonFirstClass1.isSelected()
                  && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
         int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Banglore");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
      
           miles = 7;
           Tfare= (miles*fare)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*(Pass);
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
        if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
          else if(jComboBoxDestination.getSelectedItem().equals("Hyderabad")&& jRadioButtonEconomy1.isSelected()
               && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
      int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Hyderabad");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("Binalabagan");
      
        miles = 9;
           Tfare= miles*fare;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
        if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Hyderabad") && jRadioButtonFirstClass1.isSelected()
               && jRadioButtonSingle1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) ) ){
         int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Hyderabad");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("One Way");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
      
           miles = 9;
           Tfare= (miles*fare)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Hyderabad")&& jRadioButtonEconomy1.isSelected()
               && jRadioButtonReturn1.isSelected()&& (!(jTextFieldPassenger1.getText()== null) )){
      int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
     
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Hyderabad");
       five.jTextFieldClass.setText("Economy");
       five.jTextFieldTicketType.setText("Round Trip");
       five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
       
        miles = 9;
           Tfare= miles*fare*2;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
        five.jTextFieldPrice.setText(Stotal);
           if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }
         
       }
       else if(jComboBoxDestination.getSelectedItem().equals("Hyderabad") && jRadioButtonFirstClass1.isSelected()
               && jRadioButtonReturn1.isSelected() && (!(jTextFieldPassenger1.getText()== null) )){           
         int Pass = Integer.parseInt(jTextFieldPassenger1.getText());
      
       five.jTextFieldPassengers2.setText(jTextFieldPassenger1.getText());
         five.jTextFieldTo.setText("Hyderabad");
       five.jTextFieldClass.setText("First Class");
       five.jTextFieldTicketType.setText("Round Trip");
      five.jTextFieldDate2.setText(jDateChooser.getDate().toString());
         five.jTextFieldForm.setText("New Delhi");
     
        miles = 9;
           Tfare= (miles*fare*2)+500;
           Dtax = (Tax*Tfare)/100;
           SubTotal = (Dtax + Tfare)*Pass;
          
          String Stotal = String.format("%d",SubTotal);    
       
       five.jTextFieldPrice.setText(Stotal);
      five.jTextFieldTicketType.setText("Round Trip");
         if(jComboBoxTime.getSelectedItem().equals("11:30")){
        five.jTextFieldTime2.setText("11:30");
        }else if(jComboBoxTime.getSelectedItem().equals("12:30")){
        five.jTextFieldTime2.setText("12:30");
        }
         else if(jComboBoxTime.getSelectedItem().equals("1:30")){
        five.jTextFieldTime2.setText("1:30");
        }else if(jComboBoxTime.getSelectedItem().equals("2:30")){five.jTextFieldTime2.setText("2:30");}
        else {
          five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);
        }  
       }
       else if((!jRadioButtonSingle1.isSelected() && !jRadioButtonReturn1.isSelected()) ||
               (!jRadioButtonFirstClass1.isSelected()&& !jRadioButtonEconomy1.isSelected()) ||
               jComboBoxDestination.getSelectedItem().equals("Select Destination")|| jTextFieldPassenger1.getText()== "" ){
       five.jTextFieldTo.setText(null);
       
       
       
       five.jTextFieldPrice.setText(null);
       five.jTextFieldForm.setText(null);
       five.jTextFieldDate2.setText(null);
       five.jTextFieldTime2.setText(null);
       five.jTextFieldClass.setText(null);
       five.jTextFieldPassengers2.setText(null);
       five.jTextFieldTicketType.setText(null);       
       }       
      
      
       else{
//           five.jTextFieldTo.setText(null);
//       
//       
//       
//       five.jTextFieldPrice.setText(null);
//       five.jTextFieldForm.setText(null);
//       five.jTextFieldDate2.setText(null);
//       five.jTextFieldTime2.setText(null);
//       five.jTextFieldClass.setText(null);
//       five.jTextFieldPassengers2.setText(null);
//       five.jTextFieldTicketType.setText(null);
       }
       
       
       five.jTextFieldTo.setEditable(false);
       
       
       
       five.jTextFieldPrice.setEditable(false);
       five.jTextFieldForm.setEditable(false);
       five.jTextFieldDate2.setEditable(false);
       five.jTextFieldTime2.setEditable(false);
       five.jTextFieldClass.setEditable(false);
       five.jTextFieldPassengers2.setEditable(false);
       five.jTextFieldTicketType.setEditable(false);
       
       
        
        x.setVisible(true);
        
//        six ss=new six();
//        ss.jTextFieldTotal.setText(Integer.toString(SubTotal));
//        ss.jTextFieldTax.setText(Integer.toString(Dtax));
//        ss.jTextFieldSubTotal.setText(Integer.toString(Tfare));
//        ss.setVisible(true);
        
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new three().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDestination;
    private javax.swing.JComboBox<String> jComboBoxTime;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JRadioButton jRadioButtonEconomy1;
    public static javax.swing.JRadioButton jRadioButtonFirstClass1;
    public static javax.swing.JRadioButton jRadioButtonReturn1;
    public static javax.swing.JRadioButton jRadioButtonSingle1;
    public static javax.swing.JTextField jTextFieldPassenger1;
    private rojeru_san.componentes.RSCalendar rSCalendar1;
    private rojeru_san.complementos.RSButtonHover submit;
    // End of variables declaration//GEN-END:variables
}
